apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-ip
  name: my-ip
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: my-ip
  type: LoadBalancer
status:
  loadBalancer: {}
